# TensorFlow :-

# How to Create Constant variable in TensorFlow 2.x

# Notes

### import TensorFlow

In [1]:
import tensorflow as tf

### TensorFlow Version

In [17]:
tf.__version__

'2.17.0'

### Check GPU availability

In [10]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

### Create Integer Constant

In [12]:
a = tf.constant(10)
a

<tf.Tensor: shape=(), dtype=int32, numpy=10>

### Create Float constant

In [14]:
b = tf.constant(10.2)
b

<tf.Tensor: shape=(), dtype=float32, numpy=10.2>

### create string constant

In [16]:
c = tf.constant("my name is tanzeem")
c

<tf.Tensor: shape=(), dtype=string, numpy=b'my name is tanzeem'>

### create bool constant

In [51]:
d = tf.constant(True)
d

<tf.Tensor: shape=(), dtype=bool, numpy=True>

### create constant numpy array / list / tuple

In [54]:
import numpy as np

In [56]:
np_array = tf.constant(np.array([1,2,3,4]))
np_array

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

### create 1D constant

In [59]:
t_1d = tf.constant([1,2,3,4])
t_1d

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

### create 2D constant

In [62]:
t_2d = tf.constant([[1,2],[3,4]])
t_2d

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [64]:
t_2d_1 = tf.constant([1,2,3,4],shape=(2,2),dtype="int32")
t_2d_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

### Create N-D Constant

In [67]:
t_3d_1 = tf.constant([[[1,2],[2,3],[3,4]]],dtype="int32")
t_3d_1

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[1, 2],
        [2, 3],
        [3, 4]]], dtype=int32)>

### Type of constant

In [70]:
type(t_3d_1)

tensorflow.python.framework.ops.EagerTensor

### Shape of constant

In [73]:
t_3d_1.shape

TensorShape([1, 3, 2])

### Access constant values

In [76]:
t_1d.numpy()

array([1, 2, 3, 4], dtype=int32)

In [78]:
t_1d.numpy()[3]

4

### Constant dtype

In [81]:
t_3d_1.dtype

tf.int32

# How to Create variable in TensorFlow

In [84]:
import tensorflow as tf

In [86]:
a = tf.Variable([1,2,3,4])
a 

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [88]:
a.name

'Variable:0'

In [90]:
a.shape

TensorShape([4])

In [92]:
a.dtype

tf.int32

In [94]:
a.numpy()

array([1, 2, 3, 4], dtype=int32)

In [96]:
type(a)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

### Create TF using Integer, Float, String, Bool, Complex Number

In [99]:
t_f = tf.Variable([1.2,3.3,2,3])
t_f

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1.2, 3.3, 2. , 3. ], dtype=float32)>

In [101]:
t_s = tf.Variable(["a","b","c"])
t_s

<tf.Variable 'Variable:0' shape=(3,) dtype=string, numpy=array([b'a', b'b', b'c'], dtype=object)>

In [103]:
t_b = tf.Variable(True,False)
t_b

<tf.Variable 'Variable:0' shape=() dtype=bool, numpy=True>

In [105]:
t_c = tf.Variable([4+3j])
t_c

<tf.Variable 'Variable:0' shape=(1,) dtype=complex128, numpy=array([4.+3.j])>

### Create TF from Constant TensorFlow Variable

In [108]:
t_con = tf.constant([1,2,3,4])
t_con

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [110]:
tf.Variable(t_con)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

### Create TF Variable with different shape

In [113]:
t_2d = tf.Variable([[2,3],[4,5]])
t_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [115]:
t_2d = tf.Variable([[2,3],[4,5]],shap=(2,2),dtype='float32')
t_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>

In [117]:
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [119]:
tf.reshape(a ,(2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

### Get Index of highest value

In [122]:
t_2d_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [124]:
tf.argmax(t_2d_1)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1])>

In [126]:
tf.argmax(t_2d_1).numpy()

array([1, 1])

### Viewed/convert as a tensor

In [129]:
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [131]:
tf.convert_to_tensor(a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [133]:
tf.convert_to_tensor(t_2d_1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

### Change/Assign new value to tensor

In [136]:
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [138]:
a.assign([4,5,6,7])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([4, 5, 6, 7], dtype=int32)>

In [140]:
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([4, 5, 6, 7], dtype=int32)>

### Assign Variable with anothe memory

In [143]:
a.assign_add([4,5,6,7])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([ 8, 10, 12, 14], dtype=int32)>

# How to Create Placeholder in TensorFlow 2

## How Migrate your TensorFlow 1 code to TensorFlow2

# Placeholder

In [148]:
import tensorflow as tf

In [150]:
# placeholders are not executable immediately so we need to disable eager exicution in TF 2 not in 1

In [152]:
tf.compat.v1.disable_eager_execution()

# Create Placeholder

In [155]:
a = tf.compat.v1.placeholder(dtype=tf.float32,shape=(400,400))
a

<tf.Tensor 'Placeholder:0' shape=(400, 400) dtype=float32>

In [157]:
a.dtype

tf.float32

In [159]:
a.shape

TensorShape([400, 400])

In [161]:
a.name

'Placeholder:0'

In [163]:
b = tf.compat.v1.placeholder(dtype=tf.float32,shape=(400,400))

### Perform mathematical operation with placeholder

In [166]:
c = tf.add(a, b)
c

<tf.Tensor 'Add:0' shape=(400, 400) dtype=float32>

### Create Numpy Array

In [169]:
import numpy as np

In [171]:
ones_array = np.ones ((400,400), np.float32)
ones_array

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype=float32)

### Exicute Tensorflow Placeholder using session

In [174]:
with tf.compat.v1.Session() as sess:
    d=sess.run(c,feed_dict={a:ones_array,b:ones_array})

2024-10-06 16:14:31.783545: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:388] MLIR V1 optimization pass is not enabled


In [176]:
d

array([[2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       ...,
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.]], dtype=float32)

In [178]:
type(d)

numpy.ndarray

# How to Create Sparse Tensor in TensorFlow 2X

### What is Sparse Tensor?

 #### Syntax of Sparse Tensor

In [183]:
import tensorflow as tf

### Create TensorFlow Sparse Tensor

In [186]:
st1 = tf.SparseTensor(indices=[[0,3], [2,4]], values=[10,20], dense_shape=[3,10])
st1

SparseTensor(indices=Tensor("SparseTensor/indices:0", shape=(2, 2), dtype=int64), values=Tensor("SparseTensor/values:0", shape=(2,), dtype=int32), dense_shape=Tensor("SparseTensor/dense_shape:0", shape=(2,), dtype=int64))

In [188]:
print(st1)

SparseTensor(indices=Tensor("SparseTensor/indices:0", shape=(2, 2), dtype=int64), values=Tensor("SparseTensor/values:0", shape=(2,), dtype=int32), dense_shape=Tensor("SparseTensor/dense_shape:0", shape=(2,), dtype=int64))


### Create Sparse Tensor From Dense

In [191]:
import numpy as np

In [193]:
np_array = np.array([[1,0,0,0],
                     [0,0,0,0],
                     [0,0,2,0],
                     [0,0,0,4]])
np_array

array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 4]])

In [195]:
st2_fd = tf.sparse.from_dense(np_array)
print(st2_fd )

SparseTensor(indices=Tensor("dense_to_sparse/Where:0", shape=(None, 2), dtype=int64), values=Tensor("dense_to_sparse/GatherNd:0", shape=(None,), dtype=int64), dense_shape=Tensor("dense_to_sparse/Shape:0", shape=(2,), dtype=int64))


### Extract the values, indices & shape of Sparse Tensor

In [198]:
st2_fd.values

<tf.Tensor 'dense_to_sparse/GatherNd:0' shape=(None,) dtype=int64>

In [200]:
st2_fd.indices

<tf.Tensor 'dense_to_sparse/Where:0' shape=(None, 2) dtype=int64>

# How to create Tensor with every elements are one in TensorFlow

In [203]:
import tensorflow as tf

### tf.ones()

#### Creates a tensor with all elements set to one (1).

In [207]:
ones_2dt = tf.ones((2,2),tf.float32)
ones_2dt

<tf.Tensor 'ones:0' shape=(2, 2) dtype=float32>

In [209]:
ones_3dt = tf.ones((2,2,4),tf.float32)
ones_3dt

<tf.Tensor 'ones_1:0' shape=(2, 2, 4) dtype=float32>

# tf.ones_like()

### Creates a tensor of all ones that has the same shape as the input

In [213]:
ones_2dt = tf.constant([[1,2,3],[4,5,6]])
ones_2dt

<tf.Tensor 'Const:0' shape=(2, 3) dtype=int32>

In [215]:
ones_2dt_from_cont = tf.ones_like(ones_2dt,tf.float32)
ones_2dt_from_cont

<tf.Tensor 'ones_like:0' shape=(2, 3) dtype=float32>

In [217]:
var_2dt_from_var = tf.Variable([[1,2,3],[4,5,6]])
var_2dt_from_var

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32>

In [219]:
ones_2dt_from_var = tf.ones_like(var_2dt_from_var, tf.int32)
ones_2dt_from_var

<tf.Tensor 'ones_like_1:0' shape=(2, 3) dtype=int32>

# tf.ones_initializer()

#### Initializer that generates tensors initialized to 1.

#### Initializers allow you to pre-specify an initialization strategy, encoded in the Initializer object, without knowing the shape and type of the variable being initialized.

In [224]:
import tensorflow as tf

In [226]:
def ones_variable(shape, dtype, initializer):
    return tf.Variable(initializer (shape=shape, dtype=dtype))

In [228]:
ones_variable ((2,2), tf.float32, tf.ones_initializer())

<tf.Variable 'Variable_1:0' shape=(2, 2) dtype=float32>

In [230]:
ones_variable((2,2,5), tf.int32, tf.ones_initializer())

<tf.Variable 'Variable_2:0' shape=(2, 2, 5) dtype=int32>

# How to create Tensor with every elements are zeros in TensorFlow

In [233]:
import tensorflow as tf

# tf.zero()

### Creates a tensor with all elements set to zero.

In [237]:
zeros_2dt = tf.zeros ((2,2), dtype=tf.int32)
zeros_2dt

<tf.Tensor 'zeros:0' shape=(2, 2) dtype=int32>

In [239]:
zeros_3dt = tf.zeros ((2,2,4), dtype=tf.int8)
zeros_3dt

<tf.Tensor 'zeros_1:0' shape=(2, 2, 4) dtype=int8>

# tf.zeros_like()

### Creates a tensor with all elements set to zero.

In [243]:
cont_2dt = tf.constant([[1,2,3],[4,5,6]])
cont_2dt

<tf.Tensor 'Const_1:0' shape=(2, 3) dtype=int32>

In [245]:
z1_2dt_from_cont = tf.zeros_like(cont_2dt)
z1_2dt_from_cont

<tf.Tensor 'zeros_like:0' shape=(2, 3) dtype=int32>

In [247]:
var_2dt = tf.Variable([[1,2,3], [4,5,6]])
var_2dt

<tf.Variable 'Variable_3:0' shape=(2, 3) dtype=int32>

In [249]:
z1_2dt_from_var = tf.zeros_like(var_2dt, dtype=tf.bool)
z1_2dt_from_var

<tf.Tensor 'zeros_like_1:0' shape=(2, 3) dtype=bool>

# tf.zeros_initializer()

### Initializer that generates tensors initialized to 0.

### Initializers allow you to pre-specify an initialization strategy, encoded in the Initializer object, without knowing the shape and type of the variable being initialized.

In [254]:
def zeros_variable(shape, dtype, initializer):
    return tf. Variable (initializer (shape=shape, dtype=dtype))

In [256]:
zi_t_var= zeros_variable ((2,2), tf.float32, tf.zeros_initializer())
zi_t_var

<tf.Variable 'Variable_4:0' shape=(2, 2) dtype=float32>

In [258]:
zeros_variable((3,2,5), tf.bool, tf. zeros_initializer())

<tf.Variable 'Variable_5:0' shape=(3, 2, 5) dtype=bool>